In [15]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import math
import warnings
from scipy.stats import norm
from pandas_datareader import data as pdr
import matplotlib.pyplot as plt
from datetime import date,datetime
from pandas.tseries.offsets import MonthEnd
warnings.filterwarnings('ignore')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
equity=pd.read_excel('equity.xlsx')
equity['Date'] = pd.to_datetime(equity['Date'])
equity.set_index('Date',inplace=True)
equity = equity.sort_index(ascending=True)
equity = equity.loc[(equity.index>"2000-12-30") & (equity.index<"2020-09-01")]
equity = equity.loc[equity.reset_index().groupby(equity.index.to_period('M'))['Date'].max()]
equity.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2000-12-31,1328.1547,487.3475,2342.0320,15228.5770,2080.6260,504.6200,3281.4467,13820.9664,6222.5000,6433.61,43662.0,5933.9508,100.00,100.00,NaN
2001-01-31,1375.2760,512.7057,2593.5051,16244.4792,2072.7279,617.9921,3420.7786,13880.0346,6297.5000,6795.14,45067.0,6006.1124,108.79,119.41,NaN
2001-02-28,1249.8652,479.0561,1908.7791,14918.3968,1966.0143,578.1768,3419.3794,12920.2010,5917.9000,6208.24,40036.0,5374.3006,104.83,109.40,NaN
2001-03-31,1170.6867,455.6206,1573.7061,12972.8235,2120.3623,523.2977,3260.3603,13082.8773,5633.7000,5829.95,38996.0,5187.0329,86.35,108.55,NaN
2001-04-30,1261.6511,491.2525,1855.7614,13649.8878,2127.5874,578.3639,3452.0673,14023.4773,5966.9000,6264.51,41121.0,5647.1969,84.39,118.39,NaN
2001-05-31,1270.1029,503.3238,1800.5852,13488.2385,2226.4574,613.2244,3509.9552,13347.5289,5796.1000,6123.26,38996.0,5461.6013,87.73,139.61,NaN
2001-06-30,1239.1818,520.7009,1830.9053,13357.5318,2236.7587,596.1647,3648.4891,13054.6276,5642.5000,6058.38,37315.0,5262.6804,83.14,138.05,NaN
2001-07-31,1226.9710,492.6266,1684.3645,12615.1688,1938.5602,542.4916,3475.7029,11939.0345,5529.1000,5861.19,36507.0,5124.6229,80.33,124.64,NaN
2001-08-31,1150.1637,476.7165,1470.4767,11431.0831,1852.4068,546.0578,3441.5806,10785.8113,5345.0000,5188.17,34643.0,4725.4060,79.14,130.92,NaN
2001-09-30,1057.2703,412.5298,1168.9956,10274.4329,1782.4612,480.5540,3225.2833,9870.8091,4903.4000,4308.15,29001.0,4110.3920,68.11,111.43,NaN
2001-10-31,1077.4152,436.6721,1365.5924,10418.4832,1706.1590,538.7900,3443.8576,10468.2878,5039.7000,4559.13,30595.0,4374.6791,72.66,125.37,NaN
2001-11-30,1160.0695,470.4692,1597.1121,11688.7461,1765.6545,645.0692,3561.9362,10803.3111,5203.6000,4989.91,31885.0,4510.4856,80.09,140.87,NaN
2001-12-31,1170.2312,499.5012,1578.1069,11811.4050,1667.3822,708.9699,3657.0219,10649.8731,5217.4000,5160.10,32317.0,4660.7886,80.20,155.45,NaN
2002-01-31,1153.1641,494.3066,1551.2872,11117.1506,1511.0689,764.5367,3701.9180,10100.9028,5164.8000,5107.61,32171.0,4496.8047,81.61,169.65,NaN
2002-02-28,1130.9003,480.7534,1360.3582,10867.3037,1544.5383,838.0398,3661.6704,10700.0545,5121.9788,5039.08,31820.0,4497.9334,86.72,156.69,NaN

In [17]:
Equity12monthReturn = equity.pct_change(12)
Equity12monthReturn.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2000-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,-0.118904,0.024938,-0.326180,-0.224392,-0.198615,0.404958,0.114454,-0.229441,-0.161527,-0.197946,-0.259837,-0.214556,-0.198000,0.554500,NaN
2002-01-31,-0.161504,-0.035886,-0.401857,-0.315635,-0.270976,0.237130,0.082186,-0.272271,-0.179865,-0.248344,-0.286152,-0.251295,-0.249839,0.420735,NaN
2002-02-28,-0.095182,0.003543,-0.287315,-0.271550,-0.214381,0.449452,0.070858,-0.171835,-0.134494,-0.188324,-0.205215,-0.163066,-0.172756,0.432267,NaN

In [18]:
Equity12monthReturn = Equity12monthReturn.shift()
Equity12monthReturn.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2000-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-01-31,-0.118904,0.024938,-0.326180,-0.224392,-0.198615,0.404958,0.114454,-0.229441,-0.161527,-0.197946,-0.259837,-0.214556,-0.198000,0.554500,NaN
2002-02-28,-0.161504,-0.035886,-0.401857,-0.315635,-0.270976,0.237130,0.082186,-0.272271,-0.179865,-0.248344,-0.286152,-0.251295,-0.249839,0.420735,NaN

In [19]:
Equity12monthReturn[Equity12monthReturn > 0] = 1
Equity12monthReturn[Equity12monthReturn < 0] = -1
Equity12monthReturn.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2000-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-01-31,-1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,NaN
2002-02-28,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,NaN

In [20]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
#pd.set_option('display.width', None)
#pd.set_option('display.max_colwidth', -1)
EquityMonthlyReturn = equity.pct_change()
EquityMonthlyReturn.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2000-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-01-31,0.035479,0.052033,0.107374,0.066710,-0.003796,0.224668,0.042461,0.004274,0.012053,0.056194,0.032179,0.012161,0.087900,0.194100,NaN
2001-02-28,-0.091190,-0.065631,-0.264016,-0.081633,-0.051485,-0.064427,-0.000409,-0.069152,-0.060278,-0.086371,-0.111634,-0.105195,-0.036400,-0.083829,NaN
2001-03-31,-0.063350,-0.048920,-0.175543,-0.130414,0.078508,-0.094918,-0.046505,0.012591,-0.048024,-0.060934,-0.025977,-0.034845,-0.176285,-0.007770,NaN
2001-04-30,0.077702,0.078205,0.179230,0.052191,0.003407,0.105229,0.058799,0.071895,0.059144,0.074539,0.054493,0.088714,-0.022698,0.090649,NaN
2001-05-31,0.006699,0.024572,-0.029732,-0.011843,0.046470,0.060274,0.016769,-0.048201,-0.028625,-0.022548,-0.051677,-0.032865,0.039578,0.179238,NaN
2001-06-30,-0.024345,0.034525,0.016839,-0.009690,0.004627,-0.027820,0.039469,-0.021944,-0.026501,-0.010596,-0.043107,-0.036422,-0.052320,-0.011174,NaN
2001-07-31,-0.009854,-0.053916,-0.080037,-0.055576,-0.133317,-0.090031,-0.047358,-0.085456,-0.020097,-0.032548,-0.021653,-0.026233,-0.033798,-0.097139,NaN
2001-08-31,-0.062599,-0.032296,-0.126984,-0.093862,-0.044442,0.006574,-0.009817,-0.096593,-0.033297,-0.114827,-0.051059,-0.077902,-0.014814,0.050385,NaN
2001-09-30,-0.080765,-0.134643,-0.205023,-0.101185,-0.037759,-0.119958,-0.062848,-0.084834,-0.082619,-0.169621,-0.162861,-0.130151,-0.139373,-0.148870,NaN
2001-10-31,0.019054,0.058523,0.168176,0.014020,-0.042807,0.121185,0.067769,0.060530,0.027797,0.058257,0.054964,0.064297,0.066804,0.125101,NaN
2001-11-30,0.076715,0.077397,0.169538,0.121924,0.034871,0.197255,0.034287,0.032004,0.032522,0.094487,0.042164,0.031044,0.102257,0.123634,NaN
2001-12-31,0.008760,0.061709,-0.011900,0.010494,-0.055658,0.099060,0.026695,-0.014203,0.002652,0.034107,0.013549,0.033323,0.001373,0.103500,NaN
2002-01-31,-0.014584,-0.010400,-0.016995,-0.058778,-0.093748,0.078377,0.012277,-0.051547,-0.010082,-0.010172,-0.004518,-0.035184,0.017581,0.091348,NaN
2002-02-28,-0.019307,-0.027419,-0.123078,-0.022474,0.022149,0.096141,-0.010872,0.059317,-0.008291,-0.013417,-0.010910,0.000251,0.062615,-0.076393,NaN

In [21]:
Momentum = Equity12monthReturn*EquityMonthlyReturn
Momentum = Momentum.loc[(Momentum.index> "2000-12-31")]
Momentum += 1
Momentum.head(20)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2001-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-01-31,1.014584,0.989600,1.016995,1.058778,1.093748,1.078377,1.012277,1.051547,1.010082,1.010172,1.004518,1.035184,0.982419,1.091348,NaN
2002-02-28,1.019307,1.027419,1.123078,1.022474,0.977851,1.096141,0.989128,0.940683,1.008291,1.013417,1.010910,0.999749,0.937385,0.923607,NaN
2002-03-31,0.962391,1.080357,0.931139,0.937198,0.948013,1.093920,1.008211,0.954789,0.960912,0.928914,0.941578,0.949461,1.006573,1.175378,NaN
2002-04-30,0.939358,1.009112,1.120907,0.954645,0.959620,0.940552,0.982194,0.957587,1.018158,1.065976,1.035779,1.045712,1.043761,1.090786,NaN
2002-05-31,1.007368,0.955631,1.053739,1.012727,1.089973,0.945462,1.008942,0.976360,1.013542,1.044216,1.071781,1.031725,1.063001,1.016477,NaN
2002-06-30,1.071151,1.049623,1.129866,1.062236,0.852926,0.933289,0.959692,1.096903,1.082743,1.090434,1.068076,1.082462,0.970074,0.897845,NaN
2002-07-31,1.077947,1.151038,1.084810,1.031068,1.043386,0.966703,1.040237,1.069995,1.086685,1.155713,1.099534,1.122438,1.071950,0.900240,NaN
2002-08-31,0.993456,1.002548,1.020391,1.014483,0.990249,1.025641,0.982965,1.026022,0.998282,0.996541,0.989800,1.014397,0.938466,1.032596,NaN

In [22]:
Momentum = Momentum.loc[(Momentum.index>"2001-12-31")]
Momentum

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2002-01-31,1.014584,0.989600,1.016995,1.058778,1.093748,1.078377,1.012277,1.051547,1.010082,1.010172,1.004518,1.035184,0.982419,1.091348,NaN
2002-02-28,1.019307,1.027419,1.123078,1.022474,0.977851,1.096141,0.989128,0.940683,1.008291,1.013417,1.010910,0.999749,0.937385,0.923607,NaN
2002-03-31,0.962391,1.080357,0.931139,0.937198,0.948013,1.093920,1.008211,0.954789,0.960912,0.928914,0.941578,0.949461,1.006573,1.175378,NaN
2002-04-30,0.939358,1.009112,1.120907,0.954645,0.959620,0.940552,0.982194,0.957587,1.018158,1.065976,1.035779,1.045712,1.043761,1.090786,NaN
2002-05-31,1.007368,0.955631,1.053739,1.012727,1.089973,0.945462,1.008942,0.976360,1.013542,1.044216,1.071781,1.031725,1.063001,1.016477,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-30,0.871806,0.862637,1.152325,0.955692,0.959973,0.889688,0.912137,0.932512,0.957229,0.906822,0.961813,0.959310,0.838587,0.885117,0.945933
2020-05-31,1.047630,0.934925,1.063102,1.063067,1.000671,0.957873,0.956052,0.916455,0.966421,0.933232,0.962720,0.966219,1.027810,0.913871,0.914775
2020-06-30,1.019887,0.964654,1.063679,0.926161,1.056321,1.040925,0.973873,1.020291,0.983351,0.937508,0.931819,0.945187,0.932052,1.019825,0.926079
2020-07-31,1.056382,0.972321,1.074075,0.985028,1.119596,1.066897,0.994819,0.974131,1.042032,0.999803,1.011280,1.026406,0.896179,0.973671,0.857700
2020-08-31,1.071883,0.943657,1.111602,0.974572,1.027024,1.034143,0.969602,1.066409,0.982371,1.051328,0.971624,0.965815,0.965034,0.997699,1.088909

In [23]:
TotalReturn = Momentum.prod(axis = 0)
TotalReturn = TotalReturn.to_frame()
TotalReturn = TotalReturn.transpose()
AnnualReturn = TotalReturn.pow(12/224) - 1 
AnnualReturn.index = ['Annual Return']
AnnualReturn

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Annual Return,0.061273,0.027359,0.117061,0.007172,0.018168,0.049376,0.043645,0.00823,0.046496,0.026007,0.008422,0.021704,-0.026604,0.005951,-0.071758

In [24]:
MomentumAnnual = Momentum.groupby(pd.Grouper(freq="Y")).prod()
MomentumAnnual

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
Date,,,,,,,,,,,,,,,
2002-12-31,1.088434,1.279880,1.387414,1.142797,1.135255,0.928004,1.051451,1.169137,1.232031,1.535081,1.264682,1.353556,1.222429,1.154326,1.000000
2003-12-31,1.019208,0.913959,0.985682,1.113109,0.800405,0.984523,1.009032,0.833276,0.991374,1.003490,1.020381,0.941857,1.919416,1.140371,1.000000
2004-12-31,1.108757,1.182753,1.106847,1.171412,0.925135,1.137561,1.295137,1.086359,1.112444,1.073369,1.188540,1.101350,1.191084,1.054620,1.000000
2005-12-31,1.049069,1.045117,0.876796,1.084047,1.018237,1.567997,1.240955,1.278645,1.208053,1.270714,1.201198,1.269533,1.375694,1.700018,1.000000
2006-12-31,1.157767,1.183298,0.975086,1.389660,1.988308,1.060301,1.254948,1.080900,1.144439,1.219786,1.209513,1.209697,1.510044,1.555970,1.000000
2007-12-31,1.055713,0.985734,1.191648,1.433789,1.979663,1.237113,1.174193,0.941957,1.073884,1.222892,0.968035,1.041919,1.731106,1.245037,1.000000
2008-12-31,1.330330,1.385477,1.202456,1.055844,1.227160,1.213187,1.136177,1.516562,1.108632,1.048457,1.730014,1.198327,0.840981,1.501275,1.000000
2009-12-31,0.880449,0.902689,0.726939,0.639911,0.640243,0.709670,0.748684,0.879983,0.854224,0.908208,0.815350,0.892900,0.454301,0.421124,1.000000
2010-12-31,1.150587,1.268146,1.200588,1.085812,0.558512,1.235763,1.029409,0.851654,1.126689,1.160599,0.672705,0.884050,1.209516,1.190655,1.000000
2011-12-31,1.021055,0.706302,1.036123,0.728221,0.988950,0.771882,0.859894,0.895926,0.830205,0.806700,0.847804,0.888526,0.938393,0.682436,0.640496
2012-12-31,1.068127,1.051368,1.183478,0.896416,0.905158,0.987376,1.026742,0.970516,1.066475,0.902395,1.004187,0.946338,0.667748,0.750417,0.920800
2013-12-31,1.323742,1.388219,1.369096,1.065616,1.069251,1.019623,1.219773,1.593699,1.186501,1.254817,0.993031,1.222258,0.603924,0.907826,0.941850
2014-12-31,1.136783,1.048962,1.193963,0.978055,1.624548,0.983048,1.071487,1.089566,1.007179,1.026527,1.029781,1.025418,1.048017,1.137143,0.929490
2015-12-31,0.856029,0.955868,1.097507,0.913094,1.111542,1.002824,1.100783,1.109935,0.975050,1.095605,1.157532,1.119448,0.944535,0.858289,1.516565
2016-12-31,0.979923,0.979675,0.856565,0.869332,0.696405,0.942045,0.971644,0.675605,1.043638,0.774408,0.782012,0.849164,0.817230,1.186032,0.533197
2017-12-31,1.218228,1.146277,1.329921,1.412730,1.049283,1.239290,1.134067,1.213360,1.119541,1.125126,1.244154,1.125445,1.271831,1.052043,1.241117
2018-12-31,0.956082,0.889726,1.000368,0.829663,0.955920,1.060109,0.985365,0.896966,1.009453,0.968020,1.036292,1.054855,0.754765,0.996055,0.475747
2019-12-31,1.050027,0.777860,1.394574,0.822430,0.745223,1.020049,1.156804,0.825618,0.961949,0.860352,0.910674,0.921013,0.925665,1.128606,0.934511
2020-12-31,0.847996,0.770209,1.395615,0.929627,1.052084,1.117825,0.632377,0.731453,0.927109,0.625404,0.617464,0.641381,0.478509,0.509994,1.081224

In [25]:
MomentumAnnual -= 1
MomentumAnnual.index = [2002, 2003, 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]
MomentumAnnual.head(15)

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
2002,0.088434,0.279880,0.387414,0.142797,0.135255,-0.071996,0.051451,0.169137,0.232031,0.535081,0.264682,0.353556,0.222429,0.154326,0.000000
2003,0.019208,-0.086041,-0.014318,0.113109,-0.199595,-0.015477,0.009032,-0.166724,-0.008626,0.003490,0.020381,-0.058143,0.919416,0.140371,0.000000
2004,0.108757,0.182753,0.106847,0.171412,-0.074865,0.137561,0.295137,0.086359,0.112444,0.073369,0.188540,0.101350,0.191084,0.054620,0.000000
2005,0.049069,0.045117,-0.123204,0.084047,0.018237,0.567997,0.240955,0.278645,0.208053,0.270714,0.201198,0.269533,0.375694,0.700018,0.000000
2006,0.157767,0.183298,-0.024914,0.389660,0.988308,0.060301,0.254948,0.080900,0.144439,0.219786,0.209513,0.209697,0.510044,0.555970,0.000000
2007,0.055713,-0.014266,0.191648,0.433789,0.979663,0.237113,0.174193,-0.058043,0.073884,0.222892,-0.031965,0.041919,0.731106,0.245037,0.000000
2008,0.330330,0.385477,0.202456,0.055844,0.227160,0.213187,0.136177,0.516562,0.108632,0.048457,0.730014,0.198327,-0.159019,0.501275,0.000000
2009,-0.119551,-0.097311,-0.273061,-0.360089,-0.359757,-0.290330,-0.251316,-0.120017,-0.145776,-0.091792,-0.184650,-0.107100,-0.545699,-0.578876,0.000000
2010,0.150587,0.268146,0.200588,0.085812,-0.441488,0.235763,0.029409,-0.148346,0.126689,0.160599,-0.327295,-0.115950,0.209516,0.190655,0.000000
2011,0.021055,-0.293698,0.036123,-0.271779,-0.011050,-0.228118,-0.140106,-0.104074,-0.169795,-0.193300,-0.152196,-0.111474,-0.061607,-0.317564,-0.359504
2012,0.068127,0.051368,0.183478,-0.103584,-0.094842,-0.012624,0.026742,-0.029484,0.066475,-0.097605,0.004187,-0.053662,-0.332252,-0.249583,-0.079200
2013,0.323742,0.388219,0.369096,0.065616,0.069251,0.019623,0.219773,0.593699,0.186501,0.254817,-0.006969,0.222258,-0.396076,-0.092174,-0.058150
2014,0.136783,0.048962,0.193963,-0.021945,0.624548,-0.016952,0.071487,0.089566,0.007179,0.026527,0.029781,0.025418,0.048017,0.137143,-0.070510
2015,-0.143971,-0.044132,0.097507,-0.086906,0.111542,0.002824,0.100783,0.109935,-0.024950,0.095605,0.157532,0.119448,-0.055465,-0.141711,0.516565
2016,-0.020077,-0.020325,-0.143435,-0.130668,-0.303595,-0.057955,-0.028356,-0.324395,0.043638,-0.225592,-0.217988,-0.150836,-0.182770,0.186032,-0.466803

In [29]:
MomentumStrategy = pd.concat([MomentumAnnual,AnnualReturn])
MomentumStrategy

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
2002,0.088434,0.279880,0.387414,0.142797,0.135255,-0.071996,0.051451,0.169137,0.232031,0.535081,0.264682,0.353556,0.222429,0.154326,0.000000
2003,0.019208,-0.086041,-0.014318,0.113109,-0.199595,-0.015477,0.009032,-0.166724,-0.008626,0.003490,0.020381,-0.058143,0.919416,0.140371,0.000000
2004,0.108757,0.182753,0.106847,0.171412,-0.074865,0.137561,0.295137,0.086359,0.112444,0.073369,0.188540,0.101350,0.191084,0.054620,0.000000
2005,0.049069,0.045117,-0.123204,0.084047,0.018237,0.567997,0.240955,0.278645,0.208053,0.270714,0.201198,0.269533,0.375694,0.700018,0.000000
2006,0.157767,0.183298,-0.024914,0.389660,0.988308,0.060301,0.254948,0.080900,0.144439,0.219786,0.209513,0.209697,0.510044,0.555970,0.000000
2007,0.055713,-0.014266,0.191648,0.433789,0.979663,0.237113,0.174193,-0.058043,0.073884,0.222892,-0.031965,0.041919,0.731106,0.245037,0.000000
2008,0.330330,0.385477,0.202456,0.055844,0.227160,0.213187,0.136177,0.516562,0.108632,0.048457,0.730014,0.198327,-0.159019,0.501275,0.000000
2009,-0.119551,-0.097311,-0.273061,-0.360089,-0.359757,-0.290330,-0.251316,-0.120017,-0.145776,-0.091792,-0.184650,-0.107100,-0.545699,-0.578876,0.000000
2010,0.150587,0.268146,0.200588,0.085812,-0.441488,0.235763,0.029409,-0.148346,0.126689,0.160599,-0.327295,-0.115950,0.209516,0.190655,0.000000
2011,0.021055,-0.293698,0.036123,-0.271779,-0.011050,-0.228118,-0.140106,-0.104074,-0.169795,-0.193300,-0.152196,-0.111474,-0.061607,-0.317564,-0.359504
2012,0.068127,0.051368,0.183478,-0.103584,-0.094842,-0.012624,0.026742,-0.029484,0.066475,-0.097605,0.004187,-0.053662,-0.332252,-0.249583,-0.079200
2013,0.323742,0.388219,0.369096,0.065616,0.069251,0.019623,0.219773,0.593699,0.186501,0.254817,-0.006969,0.222258,-0.396076,-0.092174,-0.058150
2014,0.136783,0.048962,0.193963,-0.021945,0.624548,-0.016952,0.071487,0.089566,0.007179,0.026527,0.029781,0.025418,0.048017,0.137143,-0.070510
2015,-0.143971,-0.044132,0.097507,-0.086906,0.111542,0.002824,0.100783,0.109935,-0.024950,0.095605,0.157532,0.119448,-0.055465,-0.141711,0.516565
2016,-0.020077,-0.020325,-0.143435,-0.130668,-0.303595,-0.057955,-0.028356,-0.324395,0.043638,-0.225592,-0.217988,-0.150836,-0.182770,0.186032,-0.466803
2017,0.218228,0.146277,0.329921,0.412730,0.049283,0.239290,0.134067,0.213360,0.119541,0.125126,0.244154,0.125445,0.271831,0.052043,0.241117
2018,-0.043918,-0.110274,0.000368,-0.170337,-0.044080,0.060109,-0.014635,-0.103034,0.009453,-0.031980,0.036292,0.054855,-0.245235,-0.003945,-0.524253
2019,0.050027,-0.222140,0.394574,-0.177570,-0.254777,0.020049,0.156804,-0.174382,-0.038051,-0.139648,-0.089326,-0.078987,-0.074335,0.128606,-0.065489
2020,-0.152004,-0.229791,0.395615,-0.070373,0.052084,0.117825,-0.367623,-0.268547,-0.072891,-0.374596,-0.382536,-0.358619,-0.521491,-0.490006,0.081224
Annual Return,0.061273,0.027359,0.117061,0.007172,0.018168,0.049376,0.043645,0.008230,0.046496,0.026007,0.008422,0.021704,-0.026604,0.005951,-0.071758

In [34]:
MomentumAnnualdata = MomentumAnnual.describe()
MomentumAnnualdata = MomentumAnnualdata.drop(MomentumAnnualdata.index[0])
MomentumStrategy = pd.concat([MomentumAnnual,MomentumAnnualdata])
MomentumStrategy = MomentumStrategy[:-5]
MomentumStrategy

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
2002,0.088434,0.279880,0.387414,0.142797,0.135255,-0.071996,0.051451,0.169137,0.232031,0.535081,0.264682,0.353556,0.222429,0.154326,0.000000
2003,0.019208,-0.086041,-0.014318,0.113109,-0.199595,-0.015477,0.009032,-0.166724,-0.008626,0.003490,0.020381,-0.058143,0.919416,0.140371,0.000000
2004,0.108757,0.182753,0.106847,0.171412,-0.074865,0.137561,0.295137,0.086359,0.112444,0.073369,0.188540,0.101350,0.191084,0.054620,0.000000
2005,0.049069,0.045117,-0.123204,0.084047,0.018237,0.567997,0.240955,0.278645,0.208053,0.270714,0.201198,0.269533,0.375694,0.700018,0.000000
2006,0.157767,0.183298,-0.024914,0.389660,0.988308,0.060301,0.254948,0.080900,0.144439,0.219786,0.209513,0.209697,0.510044,0.555970,0.000000
2007,0.055713,-0.014266,0.191648,0.433789,0.979663,0.237113,0.174193,-0.058043,0.073884,0.222892,-0.031965,0.041919,0.731106,0.245037,0.000000
2008,0.330330,0.385477,0.202456,0.055844,0.227160,0.213187,0.136177,0.516562,0.108632,0.048457,0.730014,0.198327,-0.159019,0.501275,0.000000
2009,-0.119551,-0.097311,-0.273061,-0.360089,-0.359757,-0.290330,-0.251316,-0.120017,-0.145776,-0.091792,-0.184650,-0.107100,-0.545699,-0.578876,0.000000
2010,0.150587,0.268146,0.200588,0.085812,-0.441488,0.235763,0.029409,-0.148346,0.126689,0.160599,-0.327295,-0.115950,0.209516,0.190655,0.000000
2011,0.021055,-0.293698,0.036123,-0.271779,-0.011050,-0.228118,-0.140106,-0.104074,-0.169795,-0.193300,-0.152196,-0.111474,-0.061607,-0.317564,-0.359504
2012,0.068127,0.051368,0.183478,-0.103584,-0.094842,-0.012624,0.026742,-0.029484,0.066475,-0.097605,0.004187,-0.053662,-0.332252,-0.249583,-0.079200
2013,0.323742,0.388219,0.369096,0.065616,0.069251,0.019623,0.219773,0.593699,0.186501,0.254817,-0.006969,0.222258,-0.396076,-0.092174,-0.058150
2014,0.136783,0.048962,0.193963,-0.021945,0.624548,-0.016952,0.071487,0.089566,0.007179,0.026527,0.029781,0.025418,0.048017,0.137143,-0.070510
2015,-0.143971,-0.044132,0.097507,-0.086906,0.111542,0.002824,0.100783,0.109935,-0.024950,0.095605,0.157532,0.119448,-0.055465,-0.141711,0.516565
2016,-0.020077,-0.020325,-0.143435,-0.130668,-0.303595,-0.057955,-0.028356,-0.324395,0.043638,-0.225592,-0.217988,-0.150836,-0.182770,0.186032,-0.466803
2017,0.218228,0.146277,0.329921,0.412730,0.049283,0.239290,0.134067,0.213360,0.119541,0.125126,0.244154,0.125445,0.271831,0.052043,0.241117
2018,-0.043918,-0.110274,0.000368,-0.170337,-0.044080,0.060109,-0.014635,-0.103034,0.009453,-0.031980,0.036292,0.054855,-0.245235,-0.003945,-0.524253
2019,0.050027,-0.222140,0.394574,-0.177570,-0.254777,0.020049,0.156804,-0.174382,-0.038051,-0.139648,-0.089326,-0.078987,-0.074335,0.128606,-0.065489
2020,-0.152004,-0.229791,0.395615,-0.070373,0.052084,0.117825,-0.367623,-0.268547,-0.072891,-0.374596,-0.382536,-0.358619,-0.521491,-0.490006,0.081224
mean,0.068332,0.045343,0.132140,0.029556,0.077436,0.064115,0.057838,0.033743,0.051519,0.046419,0.036492,0.036160,0.047642,0.061697,-0.041316
std,0.135950,0.200825,0.196952,0.221490,0.397433,0.189361,0.170764,0.245087,0.112197,0.211827,0.252976,0.175182,0.402239,0.330032,0.228527

In [35]:
MomentumStrategy.index = [2002, 2003, 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020, 'Annual Return', 'Annual Vol']
MomentumStrategy

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
2002,0.088434,0.279880,0.387414,0.142797,0.135255,-0.071996,0.051451,0.169137,0.232031,0.535081,0.264682,0.353556,0.222429,0.154326,0.000000
2003,0.019208,-0.086041,-0.014318,0.113109,-0.199595,-0.015477,0.009032,-0.166724,-0.008626,0.003490,0.020381,-0.058143,0.919416,0.140371,0.000000
2004,0.108757,0.182753,0.106847,0.171412,-0.074865,0.137561,0.295137,0.086359,0.112444,0.073369,0.188540,0.101350,0.191084,0.054620,0.000000
2005,0.049069,0.045117,-0.123204,0.084047,0.018237,0.567997,0.240955,0.278645,0.208053,0.270714,0.201198,0.269533,0.375694,0.700018,0.000000
2006,0.157767,0.183298,-0.024914,0.389660,0.988308,0.060301,0.254948,0.080900,0.144439,0.219786,0.209513,0.209697,0.510044,0.555970,0.000000
2007,0.055713,-0.014266,0.191648,0.433789,0.979663,0.237113,0.174193,-0.058043,0.073884,0.222892,-0.031965,0.041919,0.731106,0.245037,0.000000
2008,0.330330,0.385477,0.202456,0.055844,0.227160,0.213187,0.136177,0.516562,0.108632,0.048457,0.730014,0.198327,-0.159019,0.501275,0.000000
2009,-0.119551,-0.097311,-0.273061,-0.360089,-0.359757,-0.290330,-0.251316,-0.120017,-0.145776,-0.091792,-0.184650,-0.107100,-0.545699,-0.578876,0.000000
2010,0.150587,0.268146,0.200588,0.085812,-0.441488,0.235763,0.029409,-0.148346,0.126689,0.160599,-0.327295,-0.115950,0.209516,0.190655,0.000000
2011,0.021055,-0.293698,0.036123,-0.271779,-0.011050,-0.228118,-0.140106,-0.104074,-0.169795,-0.193300,-0.152196,-0.111474,-0.061607,-0.317564,-0.359504
2012,0.068127,0.051368,0.183478,-0.103584,-0.094842,-0.012624,0.026742,-0.029484,0.066475,-0.097605,0.004187,-0.053662,-0.332252,-0.249583,-0.079200
2013,0.323742,0.388219,0.369096,0.065616,0.069251,0.019623,0.219773,0.593699,0.186501,0.254817,-0.006969,0.222258,-0.396076,-0.092174,-0.058150
2014,0.136783,0.048962,0.193963,-0.021945,0.624548,-0.016952,0.071487,0.089566,0.007179,0.026527,0.029781,0.025418,0.048017,0.137143,-0.070510
2015,-0.143971,-0.044132,0.097507,-0.086906,0.111542,0.002824,0.100783,0.109935,-0.024950,0.095605,0.157532,0.119448,-0.055465,-0.141711,0.516565
2016,-0.020077,-0.020325,-0.143435,-0.130668,-0.303595,-0.057955,-0.028356,-0.324395,0.043638,-0.225592,-0.217988,-0.150836,-0.182770,0.186032,-0.466803
2017,0.218228,0.146277,0.329921,0.412730,0.049283,0.239290,0.134067,0.213360,0.119541,0.125126,0.244154,0.125445,0.271831,0.052043,0.241117
2018,-0.043918,-0.110274,0.000368,-0.170337,-0.044080,0.060109,-0.014635,-0.103034,0.009453,-0.031980,0.036292,0.054855,-0.245235,-0.003945,-0.524253
2019,0.050027,-0.222140,0.394574,-0.177570,-0.254777,0.020049,0.156804,-0.174382,-0.038051,-0.139648,-0.089326,-0.078987,-0.074335,0.128606,-0.065489
2020,-0.152004,-0.229791,0.395615,-0.070373,0.052084,0.117825,-0.367623,-0.268547,-0.072891,-0.374596,-0.382536,-0.358619,-0.521491,-0.490006,0.081224
Annual Return,0.068332,0.045343,0.132140,0.029556,0.077436,0.064115,0.057838,0.033743,0.051519,0.046419,0.036492,0.036160,0.047642,0.061697,-0.041316
Annual Vol,0.135950,0.200825,0.196952,0.221490,0.397433,0.189361,0.170764,0.245087,0.112197,0.211827,0.252976,0.175182,0.402239,0.330032,0.228527

In [92]:
MomentumStrategy.loc['Sharpe Ratio']= MomentumStrategy.loc['Annual Return']/MomentumStrategy.loc['Annual Vol']

In [93]:
MomentumStrategy

,SPX,RTY,NDX,HSI,SHCOMP,KOSPI,AS51,NKY,UKX,DAX,FTSEMIB,CAC,M1IN,M1RU,M1BR
2002,0.088434,0.279880,0.387414,0.142797,0.135255,-0.071996,0.051451,0.169137,0.232031,0.535081,0.264682,0.353556,0.222429,0.154326,0.000000
2003,0.019208,-0.086041,-0.014318,0.113109,-0.199595,-0.015477,0.009032,-0.166724,-0.008626,0.003490,0.020381,-0.058143,0.919416,0.140371,0.000000
2004,0.108757,0.182753,0.106847,0.171412,-0.074865,0.137561,0.295137,0.086359,0.112444,0.073369,0.188540,0.101350,0.191084,0.054620,0.000000
2005,0.049069,0.045117,-0.123204,0.084047,0.018237,0.567997,0.240955,0.278645,0.208053,0.270714,0.201198,0.269533,0.375694,0.700018,0.000000
2006,0.157767,0.183298,-0.024914,0.389660,0.988308,0.060301,0.254948,0.080900,0.144439,0.219786,0.209513,0.209697,0.510044,0.555970,0.000000
2007,0.055713,-0.014266,0.191648,0.433789,0.979663,0.237113,0.174193,-0.058043,0.073884,0.222892,-0.031965,0.041919,0.731106,0.245037,0.000000
2008,0.330330,0.385477,0.202456,0.055844,0.227160,0.213187,0.136177,0.516562,0.108632,0.048457,0.730014,0.198327,-0.159019,0.501275,0.000000
2009,-0.119551,-0.097311,-0.273061,-0.360089,-0.359757,-0.290330,-0.251316,-0.120017,-0.145776,-0.091792,-0.184650,-0.107100,-0.545699,-0.578876,0.000000
2010,0.150587,0.268146,0.200588,0.085812,-0.441488,0.235763,0.029409,-0.148346,0.126689,0.160599,-0.327295,-0.115950,0.209516,0.190655,0.000000
2011,0.021055,-0.293698,0.036123,-0.271779,-0.011050,-0.228118,-0.140106,-0.104074,-0.169795,-0.193300,-0.152196,-0.111474,-0.061607,-0.317564,-0.359504
2012,0.068127,0.051368,0.183478,-0.103584,-0.094842,-0.012624,0.026742,-0.029484,0.066475,-0.097605,0.004187,-0.053662,-0.332252,-0.249583,-0.079200
2013,0.323742,0.388219,0.369096,0.065616,0.069251,0.019623,0.219773,0.593699,0.186501,0.254817,-0.006969,0.222258,-0.396076,-0.092174,-0.058150
2014,0.136783,0.048962,0.193963,-0.021945,0.624548,-0.016952,0.071487,0.089566,0.007179,0.026527,0.029781,0.025418,0.048017,0.137143,-0.070510
2015,-0.143971,-0.044132,0.097507,-0.086906,0.111542,0.002824,0.100783,0.109935,-0.024950,0.095605,0.157532,0.119448,-0.055465,-0.141711,0.516565
2016,-0.020077,-0.020325,-0.143435,-0.130668,-0.303595,-0.057955,-0.028356,-0.324395,0.043638,-0.225592,-0.217988,-0.150836,-0.182770,0.186032,-0.466803
2017,0.218228,0.146277,0.329921,0.412730,0.049283,0.239290,0.134067,0.213360,0.119541,0.125126,0.244154,0.125445,0.271831,0.052043,0.241117
2018,-0.043918,-0.110274,0.000368,-0.170337,-0.044080,0.060109,-0.014635,-0.103034,0.009453,-0.031980,0.036292,0.054855,-0.245235,-0.003945,-0.524253
2019,0.050027,-0.222140,0.394574,-0.177570,-0.254777,0.020049,0.156804,-0.174382,-0.038051,-0.139648,-0.089326,-0.078987,-0.074335,0.128606,-0.065489
2020,-0.152004,-0.229791,0.395615,-0.070373,0.052084,0.117825,-0.367623,-0.268547,-0.072891,-0.374596,-0.382536,-0.358619,-0.521491,-0.490006,0.081224
Annual Return,0.068332,0.045343,0.132140,0.029556,0.077436,0.064115,0.057838,0.033743,0.051519,0.046419,0.036492,0.036160,0.047642,0.061697,-0.041316
Annual Vol,0.135950,0.200825,0.196952,0.221490,0.397433,0.189361,0.170764,0.245087,0.112197,0.211827,0.252976,0.175182,0.402239,0.330032,0.228527
Sharpe Ratio,0.502624,0.225785,0.670928,0.133442,0.194840,0.338587,0.338702,0.137678,0.459189,0.219134,0.144251,0.206411,0.118441,0.186942,-0.180792

In [94]:
MomentumStrategy.to_csv("Project1ReyXu.csv")